# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mw_v3.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(970, 790)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setMargin(2)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(280, 16777215))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_21 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_21.setContentsMargins(2, 12, 2, -1)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.groupBox_14 = QtGui.QGroupBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_14.sizePolicy().hasHeightForWidth())
        self.groupBox_14.setSizePolicy(sizePolicy)
        self.groupBox_14.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.gridLayout_20 = QtGui.QGridLayout(self.groupBox_14)
        self.gridLayout_20.setMargin(6)
        self.gridLayout_20.setSpacing(2)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.tableView = QtGui.QTableView(self.groupBox_14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.gridLayout_20.addWidget(self.tableView, 1, 0, 1, 1)
        self.gridGroupBox_5 = QtGui.QGroupBox(self.groupBox_14)
        self.gridGroupBox_5.setObjectName(_fromUtf8("gridGroupBox_5"))
        self.gridLayout_12 = QtGui.QGridLayout(self.gridGroupBox_5)
        self.gridLayout_12.setContentsMargins(-1, 2, -1, 2)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.pushButton_26 = QtGui.QPushButton(self.gridGroupBox_5)
        self.pushButton_26.setObjectName(_fromUtf8("pushButton_26"))
        self.gridLayout_12.addWidget(self.pushButton_26, 0, 1, 1, 1)
        self.pushButton_27 = QtGui.QPushButton(self.gridGroupBox_5)
        self.pushButton_27.setObjectName(_fromUtf8("pushButton_27"))
        self.gridLayout_12.addWidget(self.pushButton_27, 0, 0, 1, 1)
        self.pushButton_28 = QtGui.QPushButton(self.gridGroupBox_5)
        self.pushButton_28.setObjectName(_fromUtf8("pushButton_28"))
        self.gridLayout_12.addWidget(self.pushButton_28, 0, 2, 1, 1)
        self.gridLayout_20.addWidget(self.gridGroupBox_5, 0, 0, 1, 1)
        self.gridGroupBox = QtGui.QGroupBox(self.groupBox_14)
        self.gridGroupBox.setObjectName(_fromUtf8("gridGroupBox"))
        self.gridLayout_11 = QtGui.QGridLayout(self.gridGroupBox)
        self.gridLayout_11.setContentsMargins(-1, 2, -1, 2)
        self.gridLayout_11.setVerticalSpacing(0)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.checkbutt = QtGui.QPushButton(self.gridGroupBox)
        self.checkbutt.setObjectName(_fromUtf8("checkbutt"))
        self.gridLayout_11.addWidget(self.checkbutt, 0, 0, 1, 1)
        self.uncheckbutt = QtGui.QPushButton(self.gridGroupBox)
        self.uncheckbutt.setObjectName(_fromUtf8("uncheckbutt"))
        self.gridLayout_11.addWidget(self.uncheckbutt, 0, 1, 1, 1)
        self.pushButton_24 = QtGui.QPushButton(self.gridGroupBox)
        self.pushButton_24.setCheckable(True)
        self.pushButton_24.setObjectName(_fromUtf8("pushButton_24"))
        self.gridLayout_11.addWidget(self.pushButton_24, 1, 0, 1, 1)
        self.pushButton_25 = QtGui.QPushButton(self.gridGroupBox)
        self.pushButton_25.setObjectName(_fromUtf8("pushButton_25"))
        self.gridLayout_11.addWidget(self.pushButton_25, 1, 1, 1, 1)
        self.gridLayout_20.addWidget(self.gridGroupBox, 2, 0, 1, 1)
        self.gridLayout_21.addWidget(self.groupBox_14, 2, 0, 1, 1)
        self.groupBox_16 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.gridLayout_15 = QtGui.QGridLayout(self.groupBox_16)
        self.gridLayout_15.setContentsMargins(6, 2, 6, 2)
        self.gridLayout_15.setVerticalSpacing(2)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.gridGroupBox_6 = QtGui.QGroupBox(self.groupBox_16)
        self.gridGroupBox_6.setObjectName(_fromUtf8("gridGroupBox_6"))
        self.gridLayout_16 = QtGui.QGridLayout(self.gridGroupBox_6)
        self.gridLayout_16.setContentsMargins(-1, 2, -1, 2)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.pushButton_31 = QtGui.QPushButton(self.gridGroupBox_6)
        self.pushButton_31.setObjectName(_fromUtf8("pushButton_31"))
        self.gridLayout_16.addWidget(self.pushButton_31, 0, 1, 1, 1)
        self.pushButton_32 = QtGui.QPushButton(self.gridGroupBox_6)
        self.pushButton_32.setObjectName(_fromUtf8("pushButton_32"))
        self.pushButton_32.setCheckable(True)
        self.gridLayout_16.addWidget(self.pushButton_32, 0, 2, 1, 1)
        self.gridLayout_15.addWidget(self.gridGroupBox_6, 2, 0, 1, 1)
        self.gridGroupBox_7 = QtGui.QGroupBox(self.groupBox_16)
        self.gridGroupBox_7.setObjectName(_fromUtf8("gridGroupBox_7"))
        self.gridLayout_17 = QtGui.QGridLayout(self.gridGroupBox_7)
        self.gridLayout_17.setContentsMargins(-1, 2, -1, 2)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.open_raw = QtGui.QPushButton(self.gridGroupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_raw.sizePolicy().hasHeightForWidth())
        self.open_raw.setSizePolicy(sizePolicy)
        self.open_raw.setMaximumSize(QtCore.QSize(30, 30))
        self.open_raw.setObjectName(_fromUtf8("open_raw"))
        self.gridLayout_17.addWidget(self.open_raw, 1, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.gridGroupBox_7)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_17.addWidget(self.label_20, 1, 0, 1, 1)
        self.line_raw = QtGui.QLineEdit(self.gridGroupBox_7)
        self.line_raw.setMaximumSize(QtCore.QSize(180, 16777215))
        self.line_raw.setText(_fromUtf8(""))
        self.line_raw.setObjectName(_fromUtf8("line_raw"))
        self.gridLayout_17.addWidget(self.line_raw, 1, 1, 1, 1)
        self.gridLayout_15.addWidget(self.gridGroupBox_7, 0, 0, 1, 1)
        self.gridGroupBox_8 = QtGui.QGroupBox(self.groupBox_16)
        self.gridGroupBox_8.setObjectName(_fromUtf8("gridGroupBox_8"))
        self.gridLayout_18 = QtGui.QGridLayout(self.gridGroupBox_8)
        self.gridLayout_18.setContentsMargins(-1, 2, -1, 2)
        self.gridLayout_18.setHorizontalSpacing(5)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.label_23 = QtGui.QLabel(self.gridGroupBox_8)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_18.addWidget(self.label_23, 0, 4, 1, 1)
        self.label_22 = QtGui.QLabel(self.gridGroupBox_8)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_18.addWidget(self.label_22, 0, 0, 1, 1)
        self.line_alpha = QtGui.QLineEdit(self.gridGroupBox_8)
        self.line_alpha.setText(_fromUtf8(""))
        self.line_alpha.setObjectName(_fromUtf8("line_alpha"))
        self.gridLayout_18.addWidget(self.line_alpha, 0, 3, 1, 1)
        self.line_h = QtGui.QLineEdit(self.gridGroupBox_8)
        self.line_h.setObjectName(_fromUtf8("line_h"))
        self.gridLayout_18.addWidget(self.line_h, 0, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.gridGroupBox_8)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_18.addWidget(self.label_21, 0, 2, 1, 1)
        self.line_mbf = QtGui.QLineEdit(self.gridGroupBox_8)
        self.line_mbf.setText(_fromUtf8(""))
        self.line_mbf.setObjectName(_fromUtf8("line_mbf"))
        self.gridLayout_18.addWidget(self.line_mbf, 0, 5, 1, 1)
        self.gridLayout_15.addWidget(self.gridGroupBox_8, 1, 0, 1, 1)
        self.gridLayout_21.addWidget(self.groupBox_16, 0, 0, 1, 1)
        self.groupBox_15 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_15)
        self.gridLayout_2.setContentsMargins(-1, 2, -1, 2)
        self.gridLayout_2.setHorizontalSpacing(2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.widget_29 = MplWidgetT(self.groupBox_15)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_29.sizePolicy().hasHeightForWidth())
        self.widget_29.setSizePolicy(sizePolicy)
        self.widget_29.setMinimumSize(QtCore.QSize(0, 170))
        self.widget_29.setMaximumSize(QtCore.QSize(16777215, 150))
        self.widget_29.setObjectName(_fromUtf8("widget_29"))
        self.gridLayout_2.addWidget(self.widget_29, 0, 0, 1, 4)
        self.label_2 = QtGui.QLabel(self.groupBox_15)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.line_start = QtGui.QLineEdit(self.groupBox_15)
        self.line_start.setObjectName(_fromUtf8("line_start"))
        self.gridLayout_2.addWidget(self.line_start, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_15)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 2, 1, 1)
        self.line_end = QtGui.QLineEdit(self.groupBox_15)
        self.line_end.setObjectName(_fromUtf8("line_end"))
        self.gridLayout_2.addWidget(self.line_end, 1, 3, 1, 1)
        self.widget_28 = QtGui.QWidget(self.groupBox_15)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_28.sizePolicy().hasHeightForWidth())
        self.widget_28.setSizePolicy(sizePolicy)
        self.widget_28.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_28.setObjectName(_fromUtf8("widget_28"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_28)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_29 = QtGui.QPushButton(self.widget_28)
        self.pushButton_29.setObjectName(_fromUtf8("pushButton_29"))
        self.horizontalLayout_2.addWidget(self.pushButton_29)
        self.gridLayout_2.addWidget(self.widget_28, 3, 0, 1, 4)
        self.gridLayout_21.addWidget(self.groupBox_15, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(350, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widget_hold2 = QtGui.QWidget(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_hold2.sizePolicy().hasHeightForWidth())
        self.widget_hold2.setSizePolicy(sizePolicy)
        self.widget_hold2.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_hold2.setMaximumSize(QtCore.QSize(16777215, 35))
        self.widget_hold2.setObjectName(_fromUtf8("widget_hold2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_hold2)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setContentsMargins(-1, 6, -1, 6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.radioButton = QtGui.QRadioButton(self.widget_hold2)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.horizontalLayout_4.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.widget_hold2)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.horizontalLayout_4.addWidget(self.radioButton_2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_8 = QtGui.QLabel(self.widget_hold2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_4.addWidget(self.label_8)
        self.pushButton = QtGui.QPushButton(self.widget_hold2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(18, 18))
        self.line_start.setText(_fromUtf8(""))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.widget_hold2)
        self.mpl = MplWidget(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl.sizePolicy().hasHeightForWidth())
        self.mpl.setSizePolicy(sizePolicy)
        self.mpl.setMinimumSize(QtCore.QSize(300, 230))
        self.mpl.setMaximumSize(QtCore.QSize(16777212, 16777215))
        self.mpl.setObjectName(_fromUtf8("mpl"))
        self.verticalLayout.addWidget(self.mpl)
        self.lineEdit_2 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(20, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_2.setText(_fromUtf8(""))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.widget_11 = MplWidgetT(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_11.sizePolicy().hasHeightForWidth())
        self.widget_11.setSizePolicy(sizePolicy)
        self.widget_11.setMinimumSize(QtCore.QSize(0, 130))
        self.widget_11.setMaximumSize(QtCore.QSize(16777215, 130))
        self.widget_11.setObjectName(_fromUtf8("widget_11"))
        self.verticalLayout.addWidget(self.widget_11)
        self.widget_hold = QtGui.QWidget(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_hold.sizePolicy().hasHeightForWidth())
        self.widget_hold.setSizePolicy(sizePolicy)
        self.widget_hold.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_hold.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widget_hold.setObjectName(_fromUtf8("widget_hold"))
        self.gridLayout_4 = QtGui.QGridLayout(self.widget_hold)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.pushButton_6 = QtGui.QPushButton(self.widget_hold)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_6.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_4.addWidget(self.pushButton_6, 0, 2, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.widget_hold)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_5.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_4.addWidget(self.pushButton_5, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.widget_hold)
        spacerItem2 = QtGui.QSpacerItem(308, 63, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.verticalLayout.addWidget(self.pushButton_4)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 2, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.widget_2 = QtGui.QWidget(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_5.setContentsMargins(-1, 6, -1, 6)
        self.radioButton_6 = QtGui.QRadioButton(self.widget_2)
        self.radioButton_6.setMinimumSize(QtCore.QSize(0, 0))
        self.radioButton_6.setChecked(True)
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.horizontalLayout_5.addWidget(self.radioButton_6)
        self.radioButton_5 = QtGui.QRadioButton(self.widget_2)
        self.radioButton_5.setChecked(False)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.horizontalLayout_5.addWidget(self.radioButton_5)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_5 = MplWidgetPCA(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.verticalLayout_2.addWidget(self.widget_5)
        self.pushButton_7 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.verticalLayout_2.addWidget(self.pushButton_7)
        self.widget_9 = MplWidgetT(self.groupBox_3)
        self.widget_9.setObjectName(_fromUtf8("widget_9"))
        self.verticalLayout_2.addWidget(self.widget_9)
        self.widget_3 = QtGui.QWidget(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout_3.setContentsMargins(-1, 6, -1, 6)
        self.radioButton_4 = QtGui.QRadioButton(self.widget_3)
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.horizontalLayout_3.addWidget(self.radioButton_4)
        self.radioButton_3 = QtGui.QRadioButton(self.widget_3)
        self.radioButton_3.setChecked(False)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.horizontalLayout_3.addWidget(self.radioButton_3)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.label = QtGui.QLabel(self.widget_3)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit = QtGui.QLineEdit(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.widget_12 = MplWidget3(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_12.sizePolicy().hasHeightForWidth())
        self.widget_12.setSizePolicy(sizePolicy)
        self.widget_12.setMinimumSize(QtCore.QSize(0, 120))
        self.widget_12.setMaximumSize(QtCore.QSize(16777215, 120))
        self.widget_12.setObjectName(_fromUtf8("widget_12"))
        self.verticalLayout_2.addWidget(self.widget_12)
        self.gridLayout.addWidget(self.groupBox_3, 0, 2, 2, 1)
        self.textBrowser = QtGui.QTextBrowser(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 50))
        self.textBrowser.setMaximumSize(QtCore.QSize(900, 50))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.gridLayout.addWidget(self.textBrowser, 1, 0, 1, 1)
        self.groupBox_3.raise_()
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.textBrowser.raise_()
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 970, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.line_raw, self.open_raw)
        MainWindow.setTabOrder(self.open_raw, self.line_h)
        MainWindow.setTabOrder(self.line_h, self.line_alpha)
        MainWindow.setTabOrder(self.line_alpha, self.line_mbf)
        MainWindow.setTabOrder(self.line_mbf, self.pushButton_31)
        MainWindow.setTabOrder(self.pushButton_31, self.pushButton_32)
        MainWindow.setTabOrder(self.pushButton_32, self.line_start)
        MainWindow.setTabOrder(self.line_start, self.line_end)
        MainWindow.setTabOrder(self.line_end, self.pushButton_27)
        MainWindow.setTabOrder(self.pushButton_27, self.pushButton_26)
        MainWindow.setTabOrder(self.pushButton_26, self.pushButton_28)
        MainWindow.setTabOrder(self.pushButton_28, self.tableView)
        MainWindow.setTabOrder(self.tableView, self.checkbutt)
        MainWindow.setTabOrder(self.checkbutt, self.uncheckbutt)
        MainWindow.setTabOrder(self.uncheckbutt, self.pushButton_24)
        MainWindow.setTabOrder(self.pushButton_24, self.pushButton_25)
        MainWindow.setTabOrder(self.pushButton_25, self.radioButton)
        MainWindow.setTabOrder(self.radioButton, self.radioButton_2)
        MainWindow.setTabOrder(self.radioButton_2, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_5)
        MainWindow.setTabOrder(self.pushButton_5, self.pushButton_6)
        MainWindow.setTabOrder(self.pushButton_6, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.radioButton_6)
        MainWindow.setTabOrder(self.radioButton_6, self.radioButton_5)
        MainWindow.setTabOrder(self.radioButton_5, self.pushButton_7)
        MainWindow.setTabOrder(self.pushButton_7, self.radioButton_4)
        MainWindow.setTabOrder(self.radioButton_4, self.radioButton_3)
        MainWindow.setTabOrder(self.radioButton_3, self.lineEdit)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Settings", None))
        self.groupBox_14.setTitle(_translate("MainWindow", "Filtered clusters", None))
        self.pushButton_26.setText(_translate("MainWindow", "Zoom", None))
        self.pushButton_27.setText(_translate("MainWindow", "Filter", None))
        self.pushButton_28.setText(_translate("MainWindow", "Save", None))
        self.checkbutt.setText(_translate("MainWindow", "Check all", None))
        self.uncheckbutt.setText(_translate("MainWindow", "Unckeck all", None))
        self.pushButton_24.setText(_translate("MainWindow", "Flag all", None))
        self.pushButton_25.setText(_translate("MainWindow", "Unflag all", None))
        self.groupBox_16.setTitle(_translate("MainWindow", "File settings", None))
        self.pushButton_31.setText(_translate("MainWindow", "Clustering", None))
        self.pushButton_32.setText(_translate("MainWindow", "Segment", None))
        self.open_raw.setText(_translate("MainWindow", "...", None))
        self.label_20.setText(_translate("MainWindow", "Path:", None))
        self.label_23.setText(_translate("MainWindow", "mbf", None))
        self.label_22.setText(_translate("MainWindow", "h", None))
        self.label_21.setText(_translate("MainWindow", "alpha", None))
        self.groupBox_15.setTitle(_translate("MainWindow", "Time settings", None))
        self.label_2.setText(_translate("MainWindow", "Start", None))
        self.label_3.setText(_translate("MainWindow", "End", None))
        self.pushButton_29.setText(_translate("MainWindow", "Filter Segment", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Map", None))
        self.radioButton.setText(_translate("MainWindow", "Spike view", None))
        self.radioButton_2.setText(_translate("MainWindow", "Cluster view", None))
        self.label_8.setText(_translate("MainWindow", "Spike color:", None))
        self.pushButton_6.setText(_translate("MainWindow", ">>", None))
        self.pushButton_5.setText(_translate("MainWindow", "<<", None))
        self.pushButton_4.setText(_translate("MainWindow", "Hide time window", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Selected clusters", None))
        self.radioButton_6.setText(_translate("MainWindow", "Filtered view", None))
        self.radioButton_5.setText(_translate("MainWindow", "Complete view", None))
        self.pushButton_7.setText(_translate("MainWindow", "Calculate PCA", None))
        self.radioButton_4.setText(_translate("MainWindow", "Log", None))
        self.radioButton_3.setText(_translate("MainWindow", "Linear", None))
        self.label.setText(_translate("MainWindow", "Bins:", None))
        self.lineEdit.setText(_translate("MainWindow", "10", None))

from mplwidget import MplWidgetT, MplWidget, MplWidget3, MplWidgetPCA
